name: gestion_ecole
description: Une application éducative multiplateforme

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Gestion d'état
  provider: ^6.0.5
  flutter_bloc: ^9.1.1
  
  # Navigation
  go_router: ^15.1.2
  auto_route: ^9.3.0+1
  
  # HTTP & API
  dio: ^5.3.3
  retrofit: ^4.0.1
  graphql: ^5.1.0
  firebase_core: ^3.13.1
  supabase_flutter: ^2.9.0
  
  # Persistance
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  isar: ^3.1.0
  path_provider: ^2.1.1
  
  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  syncfusion_flutter_calendar: ^29.2.7
  flutter_quill: ^11.4.1
  pdf: ^3.10.0
  printing: ^5.14.2
  file_picker: ^10.1.9
  open_file: ^3.3.1
  
  # Formulaires et validation
  flutter_form_builder: ^10.0.1
  form_validator: ^2.1.1
  
  # Authentification
  firebase_auth: ^5.5.4
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1
  
  # Notifications
  flutter_local_notifications: ^19.2.1
  firebase_messaging: ^15.2.6
  
  # QR Code
  
  mobile_scanner: ^7.0.0
  
  # Internationalisation
  easy_localization: ^3.0.2
  
  # Utilitaires
  uuid: ^4.5.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4
  url_launcher: ^6.1.11
  intl_phone_number_input: ^0.7.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  local_auth: ^2.3.0
  fl_chart: ^1.0.0
  http: ^1.4.0
  share_plus: ^11.0.0

  path: any
  firebase_messaging_platform_interface: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  retrofit_generator: ^9.2.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  auto_route_generator: ^9.0.0
  flutter_lints: ^6.0.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/images/placeholders/
    - assets/fonts/
    - assets/l10n/
    - assets/mock_data/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700